### ISSUE TITLE
Rendere la ricerca case insensitive

### ISSUE THREAD

**Issue by ftrole** [SWException/products#8]
la ricerca è case sensitive

**Comment by ivanfurlan** [comment]
Nota: se si trova un modo la ricerca viene effettuata anche in: categories, taxes, customers

**Comment by ftrole** [comment]
Vedo solo ora che[ Dynamodb non supporta nativamente una cosa di questo tipo](https://stackoverflow.com/questions/44284045/query-dynamodb-with-case-insensitive-condition), credevo fosse un fix veloce da implementare ma a quanto pare no, peccato!
